# Step 1: Change port and image versions according to the question
# Step 2: kubectl create -f <this file>
# Step 3: Wait for the nginx-phpfpm pod to be in 'Running' state
# Step 4: Verify:
#         kubectl exec it nginx-phpfpm -- /bin/bash
#         In the resulting shell prompt run the following:
#         echo "<?phpinfo();?>" > /var/www/html/index.php
#         curl http://localhost:8098/
#         You should get back a valid PHPInfo HTML page.
#
# For tips on getting better at Kubernetes tasks, check out the README.md
# in this folder
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {} 
    http {
      server {
        listen 8098;
        index index.html index.htm index.php;
        root  /var/www/html;

        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
spec:
  volumes:
    - name: shared-files
      emptyDir: {}
    - name: nginx-config-volume
      configMap:
        name: nginx-config
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
    - name: php-fpm-container
      image: php:7.3-fpm
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
