#
# Step 1: kubectl create namespace node-namespace-datacenter
# Step 2: kubectl create -f <this file>
# Step 3: Wait for the pods to be in 'Running' state. Note down a pod name.
# Step 4: Verify: kubectl exec <podname> --namespace node-namespace-datacenter
#         -- curl http://localhost:8080/
#         You should get back a valid HTML content
# Step 5: Verify: Click 'Select port to view on Host 1' and provide the Node Port below.
#         You should see the page.
#
# For tips on getting better at Kubernetes tasks, check out the README.md
# in this folder
#
apiVersion: v1
kind: Service
metadata:
  name: node-service-datacenter
  namespace: node-namespace-datacenter
spec:
  type: NodePort
  selector:
    app: node-app-datacenter
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment-datacenter
  namespace: node-namespace-datacenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-datacenter
  template:
    metadata:
      labels:
        app: node-app-datacenter
    spec:
      containers:
        - name: node-container-datacenter
          image: gcr.io/kodekloud/centos-ssh-enabled:node
          ports:
            - containerPort: 80
